In [4]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [5]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [6]:
x = torch.Tensor(5, 3)
print(x)


 3.0098e+29  2.7554e+23  1.9346e-19
 4.6168e+24  1.8179e+31  7.2065e+31
 2.0283e-19  1.1046e-32  7.2728e+22
 1.7237e+25  1.8888e+31  3.3884e-12
 4.5144e+27  1.8037e+28  6.8608e+22
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix:



In [7]:
x = torch.rand(5, 3)
print(x)


 0.5672  0.8142  0.8312
 0.3079  0.9472  0.5661
 0.6744  0.5638  0.5669
 0.4666  0.4088  0.8831
 0.6354  0.4603  0.6256
[torch.FloatTensor of size 5x3]



Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)


 1.0926  1.2060  1.2256
 0.8797  1.7199  1.5035
 1.5744  0.8791  1.1619
 1.0787  1.0700  1.0347
 1.1308  1.1891  0.6359
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [10]:
print(torch.add(x, y))


 1.0926  1.2060  1.2256
 0.8797  1.7199  1.5035
 1.5744  0.8791  1.1619
 1.0787  1.0700  1.0347
 1.1308  1.1891  0.6359
[torch.FloatTensor of size 5x3]



Addition: providing an output tensor as argument



In [11]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.0926  1.2060  1.2256
 0.8797  1.7199  1.5035
 1.5744  0.8791  1.1619
 1.0787  1.0700  1.0347
 1.1308  1.1891  0.6359
[torch.FloatTensor of size 5x3]



Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)


 1.0926  1.2060  1.2256
 0.8797  1.7199  1.5035
 1.5744  0.8791  1.1619
 1.0787  1.0700  1.0347
 1.1308  1.1891  0.6359
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])


 0.8142
 0.9472
 0.5638
 0.4088
 0.4603
[torch.FloatTensor of size 5]



Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [15]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [16]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` method.



In [19]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [20]:
torch.cuda.is_available()

False

### CPU

In [1]:
import numpy as np
from timeit import default_timer as timer

def pow(a, b, c):
    for i in range(a.size):
         c[i] = a[i] ** b[i]

def main():
    vec_size = 100000000

    a = b = np.array(np.random.sample(vec_size), dtype=np.float32)
    c = np.zeros(vec_size, dtype=np.float32)

    start = timer()
    pow(a, b, c)
    duration = timer() - start

    print(duration)

if __name__ == '__main__':
    main()

34.26923434019716


### GPU

In [2]:
import numpy as np
from timeit import default_timer as timer
from numba import vectorize

@vectorize(['float32(float32, float32)'], target='cuda')
def pow(a, b):
    return a ** b

def main():
    vec_size = 100000000

    a = b = np.array(np.random.sample(vec_size), dtype=np.float32)
    c = np.zeros(vec_size, dtype=np.float32)

    start = timer()
    c = pow(a, b)
    duration = timer() - start

    print(duration)

if __name__ == '__main__':
    main()

CudaSupportError: Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBAPRO_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:

In [28]:
torch.cuda.is_available()

False