# HackerRank Numpy Questions

In [7]:
import numpy

### Arrays
Your task is to print a reversed NumPy array with the element type float.

In [2]:
def arrays(arr):
    return numpy.array(arr[::-1],dtype=float)
arr = input().strip().split(' ')
print(arrays(arr))

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### Fibonacci series

In [3]:
# Fibonacci series
a = int(input())
out =1
for i in range(1,a+1):
    out = out*i
print(out)

6
720


### Shape & Reshape 
You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [4]:
inp_arr = numpy.array(input().split(),dtype=int)
out = numpy.reshape(inp_arr,(3,3))
print(out)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose & Flatten
You are given a X integer array matrix with space separated elements (N = rows and M = columns). 
Your task is to print the transpose and flatten results.

In [5]:
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], dtype=int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### Concatenate
You are given two integer arrays of size nXp and mXp (n & m are rows, and p is the column). Your task is to concatenate the arrays along axis 0 .

In [8]:
n, m, p = map(int, input().split())
array1 = numpy.array([input().split() for _ in range(n)], dtype=int)
array2 = numpy.array([input().split() for _ in range(m)], dtype=int)
print(numpy.concatenate((array1,array2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Zeros & Ones

In [10]:
N = tuple(map(int,input().split()))
# input to numpy.zeros/ones is tuple (a,b,c)
print(numpy.zeros(N,dtype=int))
print(numpy.ones(N,dtype=int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### Eye & Identity

In [11]:
n,m = map(int,input().split())
print(numpy.eye(n,m))
print(numpy.identity(n))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Array Mathematics

In [12]:
n,m = map(int, input().split())
array1 = numpy.array([input().split() for _ in range(n)], dtype=int)
array2 = numpy.array([input().split() for _ in range(n)], dtype=int)
print(array1)
print(array2)
#Addition
print(numpy.add(array1,array2))
#Subtraction
print(numpy.subtract(array1,array2))
#Multiplication
print(numpy.multiply(array1,array2))
#Division
print(numpy.array((numpy.round(numpy.divide(array1,array2),0)),int))
#Modulus
print(numpy.mod(array1,array2))
#Power
print(numpy.power(array1,array2))

1 4
1 2 3 4
5 6 7 8
[[1 2 3 4]]
[[5 6 7 8]]
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, Ceil & Rint

In [13]:
import numpy
inp = numpy.array(input().split(),float)
print(numpy.floor(inp))
print(numpy.ceil(inp))
print(numpy.rint(inp))
#print(numpy.floor(a),numpy.ceil(a),numpy.rint(a),sep='\n')

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Sum & Product
You are given a 2-D array with dimensions NXM. 
Your task is to perform the SUM tool over axis 0 and then find the PRODUCT of that result.

In [14]:
n,m = map(int,input().split())
array = numpy.array([input().split() for _ in range(n)], dtype=int)
print(numpy.product(numpy.sum(array,axis=0)))

2 2
1 2
3 4
24


### MIN & MAX
You are given a 2-D array with dimensions NXM. 
Your task is to perform the min function over axis 1 and then find the max of that.

In [15]:
import numpy
nrow, ncol = map(int,input().split())
input = numpy.array([input().split() for _ in range (nrow)],int)
print(numpy.max(numpy.min(input,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


### Sort the input array

In [2]:
input = input().strip().split()
inp_arr = numpy.array(input,dtype=int)
sorted_arr = numpy.sort(inp_arr)
print(sorted_arr)

9 8 7 6 5 4 3 2 1 0
[0 1 2 3 4 5 6 7 8 9]


### 3rd highest element in array

In [3]:
inp_arr = numpy.random.randint(low=1,high=10,size=10)
sorted_asc = numpy.sort(inp_arr)
sorted_desc = sorted_asc[::-1]
print(sorted_desc[2])

7


### Sort the input list

In [6]:
input = input().strip().split()
inp_list = list(map(int,input))
sorted_list = sorted(inp_list,key=int)
print(sorted_list)

9 8 7 6 5 4 3 2 1 0
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Mean, Var, and Std
You are given a 2-D array of size NXM. 
Your task is to find:

The mean along axis 1
The var along axis 0
The std along axis None

In [2]:
N,M = map(int,input().split())
input = numpy.array([input().split() for _ in range(N)],dtype=int)
print(numpy.mean(input,axis=1))
print(numpy.var(input,axis=0))
print(numpy.std(input,axis=None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### Dot and Cross
You are given two arrays A and B. Both have dimensions of NXN. 
Your task is to compute their matrix product.

In [10]:
N = int(input())
arr1 = numpy.array([input().split() for _ in range(N)],int)
arr2 = numpy.array([input().split() for _ in range(N)],int)
print(numpy.dot(arr1,arr2))

2
1 2
3 4
1 2
5 6
[[11 14]
 [23 30]]


### Inner and Outer
You are given two arrays: A and B. 
Your task is to compute their inner and outer product.

In [17]:
A = numpy.array([input().split()],int)
B = numpy.array([input().split()],int)
print(numpy.inner(A,B)[0][0])
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


### Polynomials
You are given the coefficients of a polynomial P. 
Your task is to find the value of P at point x.

In [21]:
P = numpy.array(input().split(),float)
x = float(input())
print(numpy.polyval(P,x))

1.1 2 3
0
3.0


### Linear Algebra
You are given a square matrix A with dimensions NXN. Your task is to find the determinant.

In [23]:
N = int(input())
A = numpy.array([input().split() for _ in range(N)],dtype=float)
print(numpy.linalg.det(A))

2
1.1 1.1
1.1 1.1
0.0
