In [1]:
my_list=[3, 4, 5, 20, 5]
print(my_list.reverse())

None


In [2]:
print(my_list.reverse())

None


In [3]:
import numpy as np

In [4]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(a)
print(b)
print(c)

[[-0.1349122  -1.03495062 -1.46053734]
 [ 0.12225803  0.58141142 -1.73378255]]
[[-0.55985214]
 [-0.74785963]]
[[-0.69476434 -1.59480276 -2.02038948]
 [-0.6256016  -0.16644822 -2.48164218]]


In [5]:
c.shape

(2, 3)

In [6]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
#c = a*b
print(a)
print(b)
#print(c)
#c.shape

[[ 0.69527076 -0.51254514  0.61496827]
 [-0.14562493 -0.11434456  0.24845221]
 [-1.80729391  1.61937666 -0.83640553]
 [ 0.85499164  0.98612975  0.39792704]]
[[ 0.63685209  0.22812624]
 [-0.21411342 -0.59492201]
 [-0.08363778  0.41492866]]


In [7]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [8]:
a = np.random.randn(3, 4) # a.shape = (4, 3)
b = np.random.randn(4, 1) # b.shape = (3, 2)
c1 = a + b.T
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

In [9]:
print(c)
print(c1)
print(c == c1)

[[  2.90426610e-02   1.59813389e+00   7.79989359e-01 ...,   2.35259761e+01
   -7.50466013e+00   2.08074203e+01]
 [  4.32225085e-01   2.40183126e+00  -1.18441167e+00 ...,   1.99344203e+01
    3.36596451e+00   3.02806039e+00]
 [  1.86398673e+00   2.52130952e+00   3.53130990e-01 ...,  -4.85828613e+00
    1.10995164e+01  -4.66927852e+00]
 ..., 
 [ -5.12993633e+00   1.33626704e+01  -1.38868510e+01 ...,   5.56821637e+00
   -2.48288913e+01   8.30824729e+00]
 [  2.08442357e+01   1.08908945e+01   2.20767737e+00 ...,  -8.01883813e+00
    1.18843544e+01  -2.41205295e+00]
 [  9.67718340e+00   1.71578919e+01  -8.76502864e+00 ...,  -2.63128049e-01
    3.51424460e+01  -1.82857684e+01]]
[[ 0.02904266  1.59813389  0.77998936  0.69880321]
 [ 0.43222508  2.40183126 -1.18441167  0.87673425]
 [ 1.86398673  2.52130952  0.35313099 -0.16239672]]
False


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
print(c)

[[-0.21114634  0.39033337  0.95639672]
 [-0.41473067  0.70677936 -0.44654279]
 [-0.30233398 -0.62542631  1.70915224]]
[[ 0.91925651]
 [ 1.1160236 ]
 [-1.63094439]]
[[-0.19409765  0.35881649  0.8791739 ]
 [-0.46284921  0.78878245 -0.49835229]
 [ 0.49308991  1.02003553 -2.78753226]]


In [11]:
print(a)
print(b)
print(c)

[[-0.21114634  0.39033337  0.95639672]
 [-0.41473067  0.70677936 -0.44654279]
 [-0.30233398 -0.62542631  1.70915224]]
[[ 0.91925651]
 [ 1.1160236 ]
 [-1.63094439]]
[[-0.19409765  0.35881649  0.8791739 ]
 [-0.46284921  0.78878245 -0.49835229]
 [ 0.49308991  1.02003553 -2.78753226]]


In [12]:
b = b.reshape(1,3)
a.shape[0]

3

In [13]:
a = np.random.randn(3, 1)
b = np.random.randn(6, 2)
print(a)
print('\n')
print(b)
print('\n')
print(a+b)
print(np.dot(a,b))

[[-0.56224099]
 [-1.49144548]
 [ 0.07617524]]


[[ 0.3080642   0.78812383]
 [ 1.40208922  1.58421735]
 [ 0.40725812  0.5985533 ]
 [-1.42430352  0.89867589]
 [ 0.81746687  1.25576428]
 [-2.21640829  0.97567759]]




ValueError: operands could not be broadcast together with shapes (3,1) (6,2) 

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline
dirpath = 'C:/Users/ankit.bhatia/Documents/GitHub/PythonScripts/data/'

dataset = pd.read_csv(dirpath+'train.csv')
dataset = dataset.iloc[:5,[0,5,6,8,9]]
print(dataset.head(5))

In [ ]:
dataset = dataset.sort_index(ascending=False)
print(dataset.head(5))

In [ ]:
import numpy
a = numpy.array([1 2 3 4 -8 -10])
a

In [ ]:
a.sort()
a

In [ ]:
arr = input().strip().split()

In [ ]:
a = numpy.array(arr[::-1],dtype=float)
a

In [ ]:
arr = input().strip().split()
np_arr = numpy.array(arr,dtype=int)
print(numpy.reshape(np_arr,(3,3)))

In [ ]:
num_arr = numpy.ndarray((2,2),dtype=int,order='F')
print(num_arr)
print(num_arr.transpose())
print(num_arr.flatten())

In [ ]:
num_arr

In [ ]:
num_arr.transpose()

In [ ]:
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

In [ ]:
arr = [1,2,3,4]
np_arr = numpy.array(arr,dtype=int)
print('np_arr',np_arr)