In [2]:
import numpy as np

In [6]:
myData = np.arange(3,30,3)
myData

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
np.reshape(myData,(3,3),'C')

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [8]:
d = np.linspace(0, 1, 5, endpoint=False)
print(d)

[ 0.   0.2  0.4  0.6  0.8]


In [9]:
a1 = np.array(np.arange(1,5,1)) # Using np.arange function
a2 = np.array([1,2,3,4]) # Using list
print(a1)
print(a2)

[1 2 3 4]
[1 2 3 4]


In [10]:
array1=np.arange(0,100,5)
print(array1)
print (array1.size)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
20


In [23]:
mat0 = np.matrix([[1,2,3,4],[2,4,6,8]])
mat1 = np.reshape(array1,(4,5),order='C') # MATRIX USING RESHAPE FUNCTION
mat2 = np.reshape(np.arange(0,50,2),(5,5),order='F')
mat3 = np.resize(array1,(4,6)) # Matrix using resize function, it allows recyclibility like in R
mat4 = np.resize(np.random.random_sample(10),(5,5))
mat5 = np.zeros((3,3))
print(mat0)
print(mat1)
print(mat2)
print(mat3)
print(mat4)
print(mat5)

[[1 2 3 4]
 [2 4 6 8]]
[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]
[[ 0 10 20 30 40]
 [ 2 12 22 32 42]
 [ 4 14 24 34 44]
 [ 6 16 26 36 46]
 [ 8 18 28 38 48]]
[[ 0  5 10 15 20 25]
 [30 35 40 45 50 55]
 [60 65 70 75 80 85]
 [90 95  0  5 10 15]]
[[ 0.23631799  0.52753192  0.51918453  0.51679032  0.48744737]
 [ 0.04500314  0.63996625  0.35465586  0.88698523  0.18169024]
 [ 0.23631799  0.52753192  0.51918453  0.51679032  0.48744737]
 [ 0.04500314  0.63996625  0.35465586  0.88698523  0.18169024]
 [ 0.23631799  0.52753192  0.51918453  0.51679032  0.48744737]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [18]:
# sum of all elements in matrix
print(mat1.sum())
# sum of all elements in each row of matrix
print(mat1.sum(axis =0))
# sum of all elements in each column of matrix
print(mat1.sum(axis=1))
# max element in matrix
print(mat3.max())
# max element in matrix in each row
print(mat2.max(axis=0))
# max element in matrix in each column
print(mat2.max(axis=1))

950
[150 170 190 210 230]
[ 50 175 300 425]
95
[ 8 18 28 38 48]
[40 42 44 46 48]


In [19]:
print(np.identity(5))
print(np.ones((4,5)))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
