In [26]:
import numpy as np

#### Reverse a List

In [73]:
list1 = ['I', 'Love', 'Python', 'and', 'Machine', 'Learning']
list_reverse = list1[::-1]
list_reverse

['Learning', 'Machine', 'and', 'Python', 'Love', 'I']

#### List as String   

In [79]:
str1 = ' '.join(list1)
str1

'I Love Python and Machine Learning'

#### Fibonacci series

In [83]:
inp = int(input())
out =1
for i in range(1,inp+1):
    out = out * i
print(out)

4
24


### Map

#### Square It

In [4]:
l = [1,2,4,5]
list(map(lambda x: x**2,l))

[1, 4, 16, 25]

In [15]:
def square(n):
    return n**2
list(map(square,l))

[1, 4, 16, 25]

#### Create a list ‘name’ consisting of the combination of the first name and the second name from list 1 and 2 respectively. 

In [2]:
first_name = ['Ankur', 'Avik', 'Kiran', 'Nitin']
last_name = ['Narang', 'Sarkar', 'R', 'Sareen']
name = list(map(lambda x,y : x +' '+ y, first_name,last_name))
email = list(map(lambda x,y : x +'_'+ y + '@company.com', first_name,last_name))
print(name)
print(email)

['Ankur Narang', 'Avik Sarkar', 'Kiran R', 'Nitin Sareen']
['Ankur_Narang@company.com', 'Avik_Sarkar@company.com', 'Kiran_R@company.com', 'Nitin_Sareen@company.com']


#### Count the number of elements in the list starting with 's' using map

In [14]:
name = ['Ankit', 'Shikha', 'Swati', 'Nitin','Shekhar','suraj','gautam']
name_S = list(map(lambda x: 1 if x.capitalize().startswith('S') else 0,name))
print(sum(name_S))

4


#### Count the number of elements in the list starting with 's' using filter

In [24]:
name = ['Ankit', 'Shikha', 'Swati', 'Nitin','Shekhar','suraj','gautam']
name_S = list(filter(lambda x: x.capitalize().startswith('S'), name))
print(len(name_S))

4


### Filter

In [14]:
l1 = np.random.randint(1,50,10)
l1

array([ 9, 31, 12, 25, 25, 10, 26, 27, 18, 32])

In [15]:
list(filter(lambda x : x % 3==0 , l1))

[9, 12, 27, 18]

#### highest/lowest number in the list

In [44]:
a = np.random.randint(1,101,10)
print(a)
h = 0
l =0
for i in a:
    if i > h:
        h = i
    else:
        h
print('highest',h)

[35 85 26 61 84 68 22 45 44 54]
highest 85


In [54]:
b[0]

0

In [59]:
b = np.empty(len(a),dtype = 'int')
for i in range(1,len(a)):
    if a[i-1] > a[i]:
        b[i-1] = a[i-1]
    else:
        b[i-1] = a[i]
b
    

array([85, 85, 61, 84, 84, 68, 45, 45, 54,  9])

### Reduce

In [21]:
from functools import reduce

In [28]:
l2 = reduce(lambda x,y : x+y, l)
l2
#itr1 x=1, y=2, x+y=3
#itr2 x=3, y=4, x+y=7
#itr3 x=7, y=5, x+y=12

12

You are given a string and your task is to swap cases. In other words, convert all lowercase letters to uppercase letters and vice versa.

For Example:

Www.HackerRank.com → wWW.hACKERrANK.COM, 

Pythonist 2 → pYTHONIST 2

Sample Input 0

HackerRank.com presents "Pythonist 2".

Sample Output 0

hACKERrANK.COM PRESENTS "pYTHONIST 2".

In [13]:
inp = input()

In [14]:
#short
inp.swapcase()

''

In [10]:
#long
def swapCase(inp):
    a=""
    for letter in inp:
        if letter.isupper()==True:
            a+= (letter.lower())
        else:
            a+= (letter.upper())
    return a

In [11]:
swapCase(inp)

'hACKERrANK.COM PRESENTS "pYTHONIST 2".'