In [1]:
my_list=[3, 4, 5, 20, 5]
print(my_list.reverse())

None


In [2]:
print(my_list.reverse())

None


In [10]:
import numpy as np
a = np.array([58,42])
m = a.mean()
sd = a.std()
v = a.var()
ssd = sd * ((a.size)/(a.size-1))
print(m)
print(v)
print(sd)
print(np.sqrt(v))
print(ssd)

50.0
64.0
8.0
8.0
16.0


In [19]:
import pandas as pd
marks = pd.read_csv('https://query.data.world/s/HqjNNadqEnwSq1qnoV_JqyRJkc7o6O')
print(marks.isnull().sum())

Prefix         0
Assignment     2
Tutorial      12
Midterm       16
TakeHome       9
Final          5
dtype: int64


In [4]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(a)
print(b)
print(c)

[[-0.1349122  -1.03495062 -1.46053734]
 [ 0.12225803  0.58141142 -1.73378255]]
[[-0.55985214]
 [-0.74785963]]
[[-0.69476434 -1.59480276 -2.02038948]
 [-0.6256016  -0.16644822 -2.48164218]]


In [5]:
c.shape

(2, 3)

In [6]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
#c = a*b
print(a)
print(b)
#print(c)
#c.shape

[[ 0.69527076 -0.51254514  0.61496827]
 [-0.14562493 -0.11434456  0.24845221]
 [-1.80729391  1.61937666 -0.83640553]
 [ 0.85499164  0.98612975  0.39792704]]
[[ 0.63685209  0.22812624]
 [-0.21411342 -0.59492201]
 [-0.08363778  0.41492866]]


In [7]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [8]:
a = np.random.randn(3, 4) # a.shape = (4, 3)
b = np.random.randn(4, 1) # b.shape = (3, 2)
c1 = a + b.T
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

In [9]:
print(c)
print(c1)
print(c == c1)

[[  2.90426610e-02   1.59813389e+00   7.79989359e-01 ...,   2.35259761e+01
   -7.50466013e+00   2.08074203e+01]
 [  4.32225085e-01   2.40183126e+00  -1.18441167e+00 ...,   1.99344203e+01
    3.36596451e+00   3.02806039e+00]
 [  1.86398673e+00   2.52130952e+00   3.53130990e-01 ...,  -4.85828613e+00
    1.10995164e+01  -4.66927852e+00]
 ..., 
 [ -5.12993633e+00   1.33626704e+01  -1.38868510e+01 ...,   5.56821637e+00
   -2.48288913e+01   8.30824729e+00]
 [  2.08442357e+01   1.08908945e+01   2.20767737e+00 ...,  -8.01883813e+00
    1.18843544e+01  -2.41205295e+00]
 [  9.67718340e+00   1.71578919e+01  -8.76502864e+00 ...,  -2.63128049e-01
    3.51424460e+01  -1.82857684e+01]]
[[ 0.02904266  1.59813389  0.77998936  0.69880321]
 [ 0.43222508  2.40183126 -1.18441167  0.87673425]
 [ 1.86398673  2.52130952  0.35313099 -0.16239672]]
False


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
print(c)

[[-0.21114634  0.39033337  0.95639672]
 [-0.41473067  0.70677936 -0.44654279]
 [-0.30233398 -0.62542631  1.70915224]]
[[ 0.91925651]
 [ 1.1160236 ]
 [-1.63094439]]
[[-0.19409765  0.35881649  0.8791739 ]
 [-0.46284921  0.78878245 -0.49835229]
 [ 0.49308991  1.02003553 -2.78753226]]


In [11]:
print(a)
print(b)
print(c)

[[-0.21114634  0.39033337  0.95639672]
 [-0.41473067  0.70677936 -0.44654279]
 [-0.30233398 -0.62542631  1.70915224]]
[[ 0.91925651]
 [ 1.1160236 ]
 [-1.63094439]]
[[-0.19409765  0.35881649  0.8791739 ]
 [-0.46284921  0.78878245 -0.49835229]
 [ 0.49308991  1.02003553 -2.78753226]]


In [12]:
b = b.reshape(1,3)
a.shape[0]

3

In [13]:
a = np.random.randn(3, 1)
b = np.random.randn(6, 2)
print(a)
print('\n')
print(b)
print('\n')
print(a+b)
print(np.dot(a,b))

[[-0.56224099]
 [-1.49144548]
 [ 0.07617524]]


[[ 0.3080642   0.78812383]
 [ 1.40208922  1.58421735]
 [ 0.40725812  0.5985533 ]
 [-1.42430352  0.89867589]
 [ 0.81746687  1.25576428]
 [-2.21640829  0.97567759]]




ValueError: operands could not be broadcast together with shapes (3,1) (6,2) 

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline
dirpath = 'C:/Users/ankit.bhatia/Documents/GitHub/PythonScripts/data/'

dataset = pd.read_csv(dirpath+'train.csv')
dataset = dataset.iloc[:5,[0,5,6,8,9]]
print(dataset.head(5))

In [ ]:
dataset = dataset.sort_index(ascending=False)
print(dataset.head(5))

In [ ]:
import numpy
a = numpy.array([1 2 3 4 -8 -10])
a

In [ ]:
a.sort()
a

In [ ]:
arr = input().strip().split()

In [ ]:
a = numpy.array(arr[::-1],dtype=float)
a

In [ ]:
arr = input().strip().split()
np_arr = numpy.array(arr,dtype=int)
print(numpy.reshape(np_arr,(3,3)))

In [ ]:
num_arr = numpy.ndarray((2,2),dtype=int,order='F')
print(num_arr)
print(num_arr.transpose())
print(num_arr.flatten())

In [ ]:
num_arr

In [ ]:
num_arr.transpose()

In [ ]:
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

In [ ]:
arr = [1,2,3,4]
np_arr = numpy.array(arr,dtype=int)
print('np_arr',np_arr)

In [1]:
nest=[[1,2,3,4],[5,6,7],[8,9,10]]

In [6]:
nest[0:2]

[[1, 2, 3, 4], [5, 6, 7]]

In [1]:
import numpy as np
panelLength=(10,20,30,40,50,60,70,80,90,100)
panelArea = np.square(panelLength)
panelArea

array([  100,   400,   900,  1600,  2500,  3600,  4900,  6400,  8100, 10000], dtype=int32)

In [30]:
input_list=['SAS', 'R', 'PYTHON', 'SPSS']

In [31]:
input_list.remove('SPSS')
input_list.append('SPARK')

In [32]:
a = input_list

In [34]:
a = ['Pythons syntax is easy to learn', 'Pythons syntax is very clear']

In [37]:
input_str[0] + ' & ' +input_str[1]

'Pythons syntax is easy to learn & Pythons syntax is very clear'

In [40]:
 input_list =  [['SAS','R'],['Tableau','SQL'],['Python','Java']]

In [66]:
input_dict.keys()

dict_keys(['Name', 'Profession'])

In [144]:
input_dict={'Name': 'Monty', 'Profession': 'Singer' }
input_str = 'Name'
answer = input_dict.get(input_str) if type(input_dict.get(input_str))==str else 'NA'
answer

'Monty'

In [146]:
d = {'Jack Dorsey': 'Twitter', 'Tim Cook': 'Apple','Jeff Bezos': 'Amazon','Mukesh Ambani': 'RJIO'}
d.get('Tim Cook')

'Apple'

In [140]:
if type(input_dict.get(input_str))==str:
    print(input_dict.get(input_str))
else:
    print('NA')

NA


In [148]:
list_1 = [1,2,3] 
list_2 = [4,5,6] 
list_3 = [7,8,9]
import numpy as np

In [156]:
import numpy as np
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = np.multiply(array_1,array_2)
print(array_3.tolist())

[4, 10, 18]


In [157]:
input_dict = {'Jack Dorsey' : 'Twitter' , 'Tim Cook' : 'Apple','Jeff Bezos' : 'Amazon' ,'Mukesh Ambani' : 'RJIO'}

In [159]:
value_list = input_dict.values()
print(sorted(value_list))

['Amazon', 'Apple', 'RJIO', 'Twitter']


In [160]:
list1=[1,2,3,4,5,6] 
list2=[2,3,4,5,6,7,8,9]

In [168]:
set_1 = set(list1)
set_2 = set(list2)
answer_1 = set_1.difference(set_2)
answer_2 = set_1.symmetric_difference(set_2)
answer_1

{1}

In [184]:
input_str = 'alpha' 
'YES' if input_str.startswith(('a','e','i','o','u')) else 'NO'

'YES'

In [187]:
input_str = input()

#Write your code here
'YES' if input_str.startswith(('a','e','i','o','u')) else 'NO'

alpha


'YES'

In [191]:
n = int(input())
l = list()
for i in range(0,n-1):
    l[i] = i^2
print(l)

4


IndexError: list assignment index out of range

In [183]:
array_1 = np.array(list_1)
array_2 = np.array(tuple_1)

print(array_1)
print(array_2)

[1 2 3 4]
[5 6 7 8]


In [194]:
import numpy as np
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [199]:
np.arange(5,((5*10)+1),5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [201]:
def squared(x,y):
    return x**y

In [204]:
print(squared(2,3))

8


In [209]:
list_1 = [10,11,12,13]
list_2 = [15,12,13,14]
array_1 = np.array((list_1,list_2))
array_1.shape()
array_1.size()

TypeError: 'tuple' object is not callable

In [1]:
import numpy as np

In [4]:
a = np.array([2,3,4,5])
b = np.array([4, 2, 3, 8])
cosSim = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosSim

In [11]:
import numpy as np
from numpy import linalg as LA

# Create a Matrix
x = np.matrix([[1, 2, 4, 6], [2, 7, 4, 4], [3, 0, 0, 1]])

# Examine the dimensions of the matrix 
print ("The dimensions of the matrix are",x.shape)

# Examine rank and basis of matrix 
print ("The rank of this matrix is ", LA.matrix_rank(x))

The dimensions of the matrix are (3, 4)
The rank of this matrix is  3


In [12]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [29]:
x = np.matrix([[-2,11], [3,16]])
y = np.invert(x)
x*y

matrix([[ -46, -163],
        [ -61, -308]])

In [32]:
M = np.matrix([[5,4,3,6,2], [10,3,4,9,10], [7,8,3,2,8], [4,3,8,5,7],[9,7,3,3,4]])
a = ['a1','a2','a3','a4','a5']
N = [50,60,18,25,35]

ValueError: shapes (5,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [35]:
x = np.matrix([[4,9], [7,6]])

In [36]:
x/np.eye(2)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


matrix([[  4.,  inf],
        [ inf,   6.]])

In [43]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_1 = df.groupby(by = ['month','day'])['wind','rain'].mean()
print(df_1.head(20))

               wind      rain
month day                    
apr   fri  3.100000  0.000000
      mon  3.100000  0.000000
      sat  4.500000  0.000000
      sun  5.666667  0.000000
      thu  5.800000  0.000000
      wed  2.700000  0.000000
aug   fri  4.766667  0.066667
      mon  2.873333  0.000000
      sat  4.310345  0.000000
      sun  4.417500  0.025000
      thu  3.503846  0.000000
      tue  4.567857  0.300000
      wed  3.520000  0.000000
dec   fri  4.900000  0.000000
      mon  8.500000  0.000000
      sun  8.500000  0.000000
      thu  4.900000  0.000000
      tue  8.500000  0.000000
      wed  8.000000  0.000000
feb   fri  4.820000  0.000000


In [46]:
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_1 = df.pivot_table(values=['wind','rain'], index=['month','day'])
print(df_1.head(20))

               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000


In [73]:
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
round((df.isnull().sum()*100)/len(df.index),2)

Ord_id                 0.00
Prod_id                0.00
Ship_id                0.00
Cust_id                0.00
Sales                  0.24
Discount               0.65
Order_Quantity         0.65
Profit                 0.65
Shipping_Cost          0.65
Product_Base_Margin    1.30
dtype: float64

In [72]:
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
len(df.index)

8399