In [1]:
import numpy as np

In [61]:
mat_5_4 = np.reshape(np.arange(0,200,10),(5,4))
mat_4_5 = np.reshape(np.arange(10,106,5),(4,5))
mat_5_5 = np.dot(mat_5_4,mat_4_5)
mat_1_1 = np.ones(5)
print(mat_5_4)
print(mat_4_5)
print(mat_5_5)

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]
 [160 170 180 190]]
[[ 10  15  20  25  30]
 [ 35  40  45  50  55]
 [ 60  65  70  75  80]
 [ 85  90  95 100 105]]
[[ 4100  4400  4700  5000  5300]
 [11700 12800 13900 15000 16100]
 [19300 21200 23100 25000 26900]
 [26900 29600 32300 35000 37700]
 [34500 38000 41500 45000 48500]]
