In [41]:
# Importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [42]:
# To ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [43]:
# Reading the csv file and putting it into 'df' object.
df = pd.read_csv('ecommerce_consumers.csv')

In [44]:
df.head()

ratio  time   label
0   0.54  17.2  female
1   0.93  18.2    male
2   0.84  13.6  female
3   0.19   6.0    male
4   0.89  13.2  female

In [45]:
# Putting feature variable to X
X = df.drop(['label'],axis=1)

# Putting label to y
y = df['label']

In [46]:
from sklearn.model_selection import train_test_split
# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7,test_size=0.3,random_state=100)

In [64]:
# Importing classification report and confusion matrix from sklearn metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

## Logistic Regression

In [48]:
from sklearn.linear_model import LogisticRegression

logR = LogisticRegression()
logR.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [49]:
# Predicting the Test set results
y_pred_logR = logR.predict(X_test)

In [50]:
# Making the Confusion Matrix
logR_cm = confusion_matrix(y_test, y_pred_logR)
logR_cm

array([[ 0, 18],
       [ 0, 42]], dtype=int64)

In [51]:
#Let's check the overall accuracy.
logR_Score = accuracy_score( y_test, y_pred_logR)
logR_Score

0.69999999999999996

## SVM

In [52]:
from sklearn.svm import SVC

In [53]:
svm = SVC()

In [54]:
svm.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [55]:
# predict
y_pred_svm = svm.predict(X_test)

In [56]:
# Making the Confusion Matrix
svm_cm = confusion_matrix(y_test, y_pred_svm)
svm_cm

array([[16,  2],
       [ 7, 35]], dtype=int64)

In [57]:
#Let's check the overall accuracy.
svm_Score = accuracy_score( y_test, y_pred_svm)
svm_Score

0.84999999999999998

## Decision Tree

In [58]:
# Importing decision tree classifier from sklearn library
from sklearn.tree import DecisionTreeClassifier

In [59]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [62]:
# Making predictions
y_pred_dt = dt.predict(X_test)

In [67]:
# Printing classification report & confusion metrics
print(classification_report(y_test, y_pred_dt))
print(confusion_matrix(y_test,y_pred_dt))

             precision    recall  f1-score   support

     female       0.90      1.00      0.95        18
       male       1.00      0.95      0.98        42

avg / total       0.97      0.97      0.97        60

[[18  0]
 [ 2 40]]


In [68]:
# Printing accuracy
print(accuracy_score(y_test,y_pred_dt))

0.966666666667


****

In [72]:
svm_linear = SVC(kernel='linear')
svm_poly = SVC(kernel='poly')
svm_sigmoid = SVC(kernel ='sigmoid')

svm_linear.fit(X_train, y_train)
svm_poly.fit(X_train, y_train)
svm_sigmoid.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [73]:
# predict
y_pred_svm_linear = svm_linear.predict(X_test)
y_pred_svm_poly = svm_poly.predict(X_test)
y_pred_svm_sigmoid = svm_sigmoid.predict(X_test)

In [74]:
#Let's check the overall accuracy.
svm_linear_Score = accuracy_score( y_test, y_pred_svm_linear)
svm_poly_Score = accuracy_score( y_test, y_pred_svm_poly)
svm_sigmoid_Score = accuracy_score( y_test, y_pred_svm_sigmoid)
print(svm_linear_Score)
print(svm_poly_Score)
print(svm_sigmoid_Score)

0.7
0.7
0.7
